# Generated by Django 4.1 on 2022-09-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
