# Generated by Django 4.1 on 2022-09-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_groups_user_is_staff_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
