# Generated by Django 4.1 on 2022-09-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_github_user_instagram_user_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس گیتهاب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='آیدی اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس لینکدین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس توییتر'),
        ),
    ]
