# Generated by Django 4.1 on 2022-09-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_groups_remove_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
