# Generated by Django 4.1 on 2022-09-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('read_user', 'can read a user'),), 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
    ]
