# Generated by Django 4.1 on 2022-09-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
