# Generated by Django 4.1 on 2022-09-05 09:36

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_alter_video_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
