# Generated by Django 4.1 on 2022-09-11 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created'], 'verbose_name': 'لایک', 'verbose_name_plural': 'لایک\u200cها'},
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 16, 17, 59, 313984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='video.video', verbose_name='ویدئو'),
        ),
    ]
