# Generated by Django 4.1 on 2022-09-11 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_video_slug_alter_like_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.AlterField(
            model_name='like',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 16, 40, 13, 454334, tzinfo=datetime.timezone.utc)),
        ),
    ]
