# Generated by Django 4.1 on 2022-09-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='related_video',
            new_name='comment',
        ),
    ]
