# Generated by Django 4.1 on 2022-09-17 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0017_rename_related_video_notification_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-video__id'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ManyToManyField(null=True, related_name='notification_receiver', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده'),
        ),
    ]
