# Generated by Django 4.1 on 2022-09-17 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0019_usernotification_delete_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'verbose_name': 'پیام خصوصی', 'verbose_name_plural': 'پیام\u200cهای خصوصی'},
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='message',
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notif_receiver', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notif_sender', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('receiver', models.ManyToManyField(null=True, related_name='admin_notif_receiver', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notif_sender', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'اعلان سایت',
                'verbose_name_plural': 'اعلانات سایت',
            },
        ),
    ]
