# Generated by Django 4.1 on 2022-09-17 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0020_alter_usernotification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان سایت', 'verbose_name_plural': 'اعلانات سایت'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام خصوصی', 'verbose_name_plural': 'پیام\u200cهای خصوصی'},
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 19, 36, 50, 12229), null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 19, 36, 50, 12073), null=True),
        ),
    ]
