# Generated by Django 4.1 on 2022-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_alter_adminnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
