# Generated by Django 4.1 on 2022-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0022_alter_adminnotification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='عنوان'),
        ),
    ]
