# Generated by Django 4.1 on 2022-09-19 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0025_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='video.video', verbose_name='ویدئو'),
        ),
    ]
