# Generated by Django 4.1 on 2022-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0028_ipaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={},
        ),
        migrations.AddField(
            model_name='video',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='video.ipaddress', verbose_name='بازدیدها'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='آدرس آی پی'),
        ),
    ]
