# Generated by Django 4.1 on 2022-09-21 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0029_alter_ipaddress_options_video_hits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favorites',
            field=models.ManyToManyField(blank=None, default=None, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='مورد علاقه\u200cها'),
        ),
    ]
