# Generated by Django 4.1 on 2022-11-28 09:07

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0030_video_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود ویدئو'),
        ),
        migrations.AlterField(
            model_name='video',
            name='like_count',
            field=models.BigIntegerField(default='0', verbose_name='تعداد لایک\u200cها'),
        ),
    ]
